base.url=https://sandbox.wompi.co/v1
public.key=pub_test_Aj6ON025rnZ5SOF1w5OIMWxymnJFuXNX
private.key=prv_test_95uumLe2r1gCcxi4X8NBQkmtrKipPM4L
integrity.key=test_integrity_kMuygkr7xAA3q07a1dPwsBgJYEhpiwVQ